# Iris data를 Logistic Regression으로 분류하는 모델 생성

In [9]:
from sklearn.datasets import load_iris
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import LogisticRegression

In [2]:
iris = load_iris()
iris_scaled = MinMaxScaler().fit_transform(iris.data)
iris_scaled[:3]

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667]])

In [3]:
iris.data[:3]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2]])

### 1. Scaler 저장

In [4]:
X_train, X_test, y_train, y_test = train_test_split(
    iris.data, iris.target, stratify=iris.target, test_size=0.2, random_state=2022
)

In [5]:
X_test[:3]

array([[7.1, 3. , 5.9, 2.1],
       [4.8, 3.4, 1.9, 0.2],
       [6.7, 3. , 5. , 1.7]])

In [6]:
y_test[:3]

array([2, 0, 1])

In [7]:
scaler = MinMaxScaler()
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)

In [14]:
# scaler 저장
import joblib
joblib.dump(scaler, 'iris_scaler.pkl')

['iris_scaler.pkl']

### 2. Model 저장

In [10]:
lr = LogisticRegression(random_state=2022)

In [11]:
params = {
    'C': [0.1, 1, 5, 10]
}
grid_cv = GridSearchCV(lr, param_grid=params, scoring='accuracy', cv=5)
grid_cv.fit(X_train_scaled, y_train)
grid_cv.best_params_

{'C': 10}

In [12]:
best_lr = grid_cv.best_estimator_
joblib.dump(best_lr, 'iris_best_lr.pkl')

['iris_best_lr.pkl']

### 3. Test code

In [17]:
import numpy as np
test_array = np.array([7.1, 3. , 5.9, 2.1])

In [18]:
new_scaler = joblib.load('iris_scaler.pkl')
test_scaled = new_scaler.transform(test_array.reshape(1,-1))

In [19]:
test_scaled

array([[0.82352941, 0.41666667, 0.83050847, 0.83333333]])

In [20]:
new_lr = joblib.load('iris_best_lr.pkl')
pred = new_lr.predict(test_scaled)
pred

array([2])

In [21]:
result = iris.target_names[pred[0]]
result

'virginica'

In [22]:
!mv iris_best_lr.pkl iris_scaler.pkl drive/MyDrive/project/static/model